Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from cobra.io import read_sbml_model
model = read_sbml_model("../../tests/gem/ecoli_core.zip")
G = cn.Graph.from_cobra_model(model)
G.shape
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcobra[39;00m[38;5;21;01m.[39;00m[38;5;21;01mio[39;00m [38;5;28;01mimport[39;00m read_sbml_model
[0;32m----> 2[0m model [38;5;241m=[39m [43mread_sbml_model[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m../../tests/gem/ecoli_core.zip[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      3[0m G [38;5;241m=[39m cn[38;5;241m.[39mGraph[38;5;241m.[39mfrom_cobra_model(model)
[1;32m      4[0m G[38;5;241m.[39mshape

File [0;32m~/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/cobra/io/sbml.py:460[0m, in [0;36mread_sbml_model[0;34m(filename, number, f_replace, **kwargs)[0m
[1;32m    458[0m     [38;5;28;01mreturn[39;00m _sbml_to_model(doc, number[38;5;241m=[39mnumber, f_replace[38;5;241m=[39mf_replace, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m    459[0m [38;5;28;01mexcept[39;00m [38;5;167;01mIOError[39;00m [38;5;28;01mas[39;00m e:
[0;32m--> 460[0m     [38;5;28;01mraise[39;00m e
[1;32m    462[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m original_error:
[1;32m    463[0m     cobra_error [38;5;241m=[39m CobraSBMLError(
[1;32m    464[0m         [38;5;124m"[39m[38;5;124mSomething went wrong reading the SBML model. Most likely the SBML[39m[38;5;124m"[39m
[1;32m    465[0m         [38;5;124m"[39m[38;5;124m model is not valid. Please check that your model is valid using [39m[38;5;124m"[39m
[0;32m   (...)[0m
[1;32m    470[0m         [38;5;124m"[39m[38;5;124mat https://github.com/opencobra/cobrapy/issues .[39m[38;5;124m"[39m
[1;32m    471[0m     )

File [0;32m~/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/cobra/io/sbml.py:457[0m, in [0;36mread_sbml_model[0;34m(filename, number, f_replace, **kwargs)[0m
[1;32m    402[0m [38;5;250m[39m[38;5;124;03m"""Read SBML model from given filename.[39;00m
[1;32m    403[0m 
[1;32m    404[0m [38;5;124;03mIf the given filename ends with the suffix ''.gz'' (for example,[39;00m
[0;32m   (...)[0m
[1;32m    454[0m [38;5;124;03mFile handles to compressed files are not supported yet.[39;00m
[1;32m    455[0m [38;5;124;03m"""[39;00m
[1;32m    456[0m [38;5;28;01mtry[39;00m:
[0;32m--> 457[0m     doc [38;5;241m=[39m [43m_get_doc_from_filename[49m[43m([49m[43mfilename[49m[43m)[49m
[1;32m    458[0m     [38;5;28;01mreturn[39;00m _sbml_to_model(doc, number[38;5;241m=[39mnumber, f_replace[38;5;241m=[39mf_replace, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m    459[0m [38;5;28;01mexcept[39;00m [38;5;167;01mIOError[39;00m [38;5;28;01mas[39;00m e:

File [0;32m~/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/cobra/io/sbml.py:504[0m, in [0;36m_get_doc_from_filename[0;34m(filename)[0m
[1;32m    501[0m         doc: libsbml[38;5;241m.[39mSBMLDocument [38;5;241m=[39m libsbml[38;5;241m.[39mreadSBMLFromFile(filename)
[1;32m    502[0m     [38;5;28;01melse[39;00m:
[1;32m    503[0m         [38;5;66;03m# string representation[39;00m
[0;32m--> 504[0m         [38;5;28;01mraise[39;00m [38;5;167;01mIOError[39;00m(
[1;32m    505[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mThe file with [39m[38;5;124m'[39m[38;5;132;01m{[39;00mfilename[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m does not exist, [39m[38;5;124m"[39m
[1;32m    506[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mor is not an SBML string. Provide the path to [39m[38;5;124m"[39m
[1;32m    507[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124man existing SBML file or a valid SBML string representation:[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m    508[0m         )
[1;32m    509[0m [38;5;28;01melif[39;00m [38;5;28mhasattr[39m(filename, [38;5;124m"[39m[38;5;124mread[39m[38;5;124m"[39m):
[1;32m    510[0m     [38;5;66;03m# file handle[39;00m
[1;32m    511[0m     doc: libsbml[38;5;241m.[39mSBMLDocument [38;5;241m=[39m libsbml[38;5;241m.[39mreadSBMLFromString(filename[38;5;241m.[39mread())

[0;31mOSError[0m: The file with '../../tests/gem/ecoli_core.zip' does not exist, or is not an SBML string. Provide the path to an existing SBML file or a valid SBML string representation:


